version: '3'

services:
  express-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-server
    ports:
      - "3000:3000"

  ngrok:
    restart: always
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=2X48Q9vJcZxqp8D5fBtd2_4qtvVUjof8kiMqpNGHFqi
    command: http host.docker.internal:3000 --domain=mbl.ngrok.app
    extra_hosts:
      - "host.docker.internal:host-gateway"
